name: wacoproject
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  numberpicker:
  flutter_launcher_icons:
  animated_splash_screen:
  get:
  introduction_screen:
  chips_choice:
  firebase_database:
  firebase_core:
  pinput:
  cloud_firestore:
  rflutter_alert:
  intl:
  uuid:
  shared_preferences:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/

fonts:
  - family: NotoSansKR
    fonts:
      - asset: fonts/NotoSansKR-Light.otf
      - asset: fonts/NotoSansKR-Black.otf
      - asset: fonts/NotoSansKR-Bold.otf
      - asset: fonts/NotoSansKR-Medium.otf
      - asset: fonts/NotoSansKR-Thin.otf
      - asset: fonts/NotoSansKR-Regular.otf
